name: Bump Version

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read and bump version in GNUmakefile
        run: |
            # Read current version from GNUmakefile
            CURRENT_VERSION=$(grep -E "^VERSION\s*=" GNUmakefile | awk -F '=' '{print $2}' | xargs)
            echo "Current version: $CURRENT_VERSION"
  
            # Increment the patch version
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "Bumping version to: $NEW_VERSION"
  
            # Update the GNUmakefile with the new version
            sed -i "s/^VERSION\s*=.*/VERSION = $NEW_VERSION/" GNUmakefile
  
      - name: Commit and push changes
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -am "Bump version to $NEW_VERSION"
            git push
